CREATE TABLE CUSTOMER (
ID bigint(20) NOT NULL AUTO_INCREMENT,
ADDRESS_LINE_ONE varchar(100) NOT NULL,
ADDRESS_LINE_TWO varchar(50) NOT NULL,
CITY varchar(50) DEFAULT NULL,
EMAIL varchar(50) DEFAULT NULL,
FIRST_NAME varchar(50) DEFAULT NULL,
LAST_NAME varchar(50) DEFAULT NULL,
PHONE_NUMBER varchar(50) DEFAULT NULL,
STATE varchar(50) DEFAULT NULL,
ZIP_CODE varchar(50) DEFAULT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE PRODUCT (
ID bigint(20) NOT NULL AUTO_INCREMENT,
DESCRIPTION varchar(100) NOT NULL ,
PRICE decimal(20,2) NOT NULL,
IMAGE_URL varchar(100) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO CUSTOMER (ID,ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,CITY,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,STATE,ZIP_CODE) VALUES(NULL,'Adrress_1', 'ADDRRESS_2', 'B-STOK','FAJNY@FAIL.COM','DOGGO', 'LOL','666','SOLID','19-999');
INSERT INTO CUSTOMER (ID,ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,CITY,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,STATE,ZIP_CODE) VALUES(NULL,'Adrress_1', 'ADDRRESS_2', 'B-STOK','FAJNY@FAIL.COM','DOGGO', 'LOL','666','SOLID','19-999');
INSERT INTO CUSTOMER (ID,ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,CITY,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,STATE,ZIP_CODE) VALUES(NULL,'Adrress_1', 'ADDRRESS_2', 'B-STOK','FAJNY@FAIL.COM','DOGGO', 'LOL','666','SOLID','19-999');
INSERT INTO CUSTOMER (ID,ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,CITY,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,STATE,ZIP_CODE) VALUES(NULL,'Adrress_1', 'ADDRRESS_2', 'B-STOK','FAJNY@FAIL.COM','DOGGO', 'LOL','666','SOLID','19-999');


INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE,IMAGE_URL) VALUES(NULL,'OPIS PRODUKTU',20.0,'http://img.com/prodId=1');
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE,IMAGE_URL) VALUES(NULL,'OPIS PRODUKTU',20.0,'http://img.com/prodId=1');
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE,IMAGE_URL) VALUES(NULL,'OPIS PRODUKTU',20.0,'http://img.com/prodId=1');
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE,IMAGE_URL) VALUES(NULL,'OPIS PRODUKTU',20.0,'http://img.com/prodId=1');